# Form implementation generated from reading ui file 'Event.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ClickMe(object):
    def setupUi(self, ClickMe):
        ClickMe.setObjectName("ClickMe")
        ClickMe.resize(371, 204)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        ClickMe.setFont(font)
        self.label = QtWidgets.QLabel(ClickMe)
        self.label.setGeometry(QtCore.QRect(30, 90, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(19)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(ClickMe)
        self.widget.setGeometry(QtCore.QRect(30, 30, 321, 33))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.button_clickme = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_clickme.sizePolicy().hasHeightForWidth())
        self.button_clickme.setSizePolicy(sizePolicy)
        self.button_clickme.setAutoRepeatInterval(200)
        self.button_clickme.setObjectName("button_clickme")
        self.horizontalLayout.addWidget(self.button_clickme)

        self.button_clickme.clicked.connect(self.click_me)

        self.retranslateUi(ClickMe)
        QtCore.QMetaObject.connectSlotsByName(ClickMe)

    def click_me(self):
        my_text = self.lineEdit.text()
        self.label.setText(my_text)

    def retranslateUi(self, ClickMe):
        _translate = QtCore.QCoreApplication.translate
        ClickMe.setWindowTitle(_translate("ClickMe", "QT App"))
        self.lineEdit.setPlaceholderText(_translate("ClickMe", "Please enter your name! "))
        self.button_clickme.setText(_translate("ClickMe", "Click Me!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ClickMe = QtWidgets.QWidget()
    ui = Ui_ClickMe()
    ui.setupUi(ClickMe)
    ClickMe.show()
    sys.exit(app.exec())
