from PyQt6 import QtCore, QtGui, QtWidgets
import os

basedir = os.path.dirname(__file__)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(920, 550)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.TabShape.Triangular)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalWidget = QtWidgets.QWidget(self.tab)
        self.horizontalWidget.setStyleSheet("QWidget{\n"
"\n"
"background-color:rgb(218,218,218)\n"
"\n"
"}")
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_book_id = QtWidgets.QLineEdit(self.horizontalWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_book_id.setFont(font)
        self.lineEdit_book_id.setText("")
        self.lineEdit_book_id.setObjectName("lineEdit_book_id")
        self.horizontalLayout_2.addWidget(self.lineEdit_book_id)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_book_name = QtWidgets.QLabel(self.horizontalWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_book_name.setFont(font)
        self.label_book_name.setObjectName("label_book_name")
        self.verticalLayout_2.addWidget(self.label_book_name)
        self.label_book_author = QtWidgets.QLabel(self.horizontalWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_book_author.setFont(font)
        self.label_book_author.setObjectName("label_book_author")
        self.verticalLayout_2.addWidget(self.label_book_author)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addWidget(self.horizontalWidget)
        self.horizontalWidget_2 = QtWidgets.QWidget(self.tab)
        self.horizontalWidget_2.setStyleSheet("QWidget{\n"
"\n"
"background-color:rgb(218,218,218)\n"
"\n"
"}")
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalWidget_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_member_id = QtWidgets.QLineEdit(self.horizontalWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_member_id.setFont(font)
        self.lineEdit_member_id.setText("")
        self.lineEdit_member_id.setObjectName("lineEdit_member_id")
        self.horizontalLayout_3.addWidget(self.lineEdit_member_id)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_meber_name = QtWidgets.QLabel(self.horizontalWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_meber_name.setFont(font)
        self.label_meber_name.setObjectName("label_meber_name")
        self.verticalLayout_3.addWidget(self.label_meber_name)
        self.label_contact_info = QtWidgets.QLabel(self.horizontalWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_contact_info.setFont(font)
        self.label_contact_info.setObjectName("label_contact_info")
        self.verticalLayout_3.addWidget(self.label_contact_info)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addWidget(self.horizontalWidget_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.toolButton_issue = QtWidgets.QToolButton(self.tab)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.join(basedir, "images", "issuebook.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolButton_issue.setIcon(icon)
        self.toolButton_issue.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_issue.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.toolButton_issue.setObjectName("toolButton_issue")
        self.horizontalLayout_5.addWidget(self.toolButton_issue)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lineEdit_submission = QtWidgets.QLineEdit(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_submission.setFont(font)
        self.lineEdit_submission.setStyleSheet("QLineEdit{\n"
"\n"
"background-color:rgb(218,218,218)\n"
"\n"
"}")
        self.lineEdit_submission.setObjectName("lineEdit_submission")
        self.verticalLayout_5.addWidget(self.lineEdit_submission)
        self.tableWidget_book_info = QtWidgets.QTableWidget(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tableWidget_book_info.setFont(font)
        self.tableWidget_book_info.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.tableWidget_book_info.setStyleSheet("QTableWidget{\n"
"\n"
"background-color:rgb(218,218,218)\n"
"\n"
"}")
        self.tableWidget_book_info.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.tableWidget_book_info.setAutoScroll(True)
        self.tableWidget_book_info.setObjectName("tableWidget_book_info")
        self.tableWidget_book_info.setColumnCount(4)
        self.tableWidget_book_info.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_book_info.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_book_info.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_book_info.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_book_info.setHorizontalHeaderItem(3, item)
        self.tableWidget_book_info.horizontalHeader().setDefaultSectionSize(185)
        self.verticalLayout_5.addWidget(self.tableWidget_book_info)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.toolButton_renew = QtWidgets.QToolButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.toolButton_renew.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(os.path.join(basedir, "images", "renew.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolButton_renew.setIcon(icon1)
        self.toolButton_renew.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_renew.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.toolButton_renew.setObjectName("toolButton_renew")
        self.horizontalLayout_6.addWidget(self.toolButton_renew)
        self.toolButton_submit_book = QtWidgets.QToolButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.toolButton_submit_book.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(os.path.join(basedir, "images", "submission.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolButton_submit_book.setIcon(icon2)
        self.toolButton_submit_book.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_submit_book.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.toolButton_submit_book.setObjectName("toolButton_submit_book")
        self.horizontalLayout_6.addWidget(self.toolButton_submit_book)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolButton_add_member = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_add_member.setMaximumSize(QtCore.QSize(145, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.toolButton_add_member.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(os.path.join(basedir, "images", "addmember.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolButton_add_member.setIcon(icon3)
        self.toolButton_add_member.setIconSize(QtCore.QSize(68, 68))
        self.toolButton_add_member.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.toolButton_add_member.setObjectName("toolButton_add_member")
        self.verticalLayout.addWidget(self.toolButton_add_member)
        self.toolButton_add_book = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_add_book.setMaximumSize(QtCore.QSize(145, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.toolButton_add_book.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(os.path.join(basedir, "images", "addbook.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolButton_add_book.setIcon(icon4)
        self.toolButton_add_book.setIconSize(QtCore.QSize(68, 68))
        self.toolButton_add_book.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.toolButton_add_book.setObjectName("toolButton_add_book")
        self.verticalLayout.addWidget(self.toolButton_add_book)
        self.toolButton_view_books = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_view_books.setMaximumSize(QtCore.QSize(145, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.toolButton_view_books.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(os.path.join(basedir, "images", "viewbook .png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolButton_view_books.setIcon(icon5)
        self.toolButton_view_books.setIconSize(QtCore.QSize(68, 68))
        self.toolButton_view_books.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.toolButton_view_books.setObjectName("toolButton_view_books")
        self.verticalLayout.addWidget(self.toolButton_view_books)
        self.toolButton_view_memers = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_view_memers.setMaximumSize(QtCore.QSize(145, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.toolButton_view_memers.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(os.path.join(basedir, "images", "viewmembers.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolButton_view_memers.setIcon(icon6)
        self.toolButton_view_memers.setIconSize(QtCore.QSize(68, 68))
        self.toolButton_view_memers.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.toolButton_view_memers.setObjectName("toolButton_view_memers")
        self.verticalLayout.addWidget(self.toolButton_view_memers)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Library System Managment"))
        self.lineEdit_book_id.setPlaceholderText(_translate("MainWindow", "Please Enter Book ID"))
        self.label_book_name.setText(_translate("MainWindow", "Book name"))
        self.label_book_author.setText(_translate("MainWindow", "Book Author"))
        self.lineEdit_member_id.setPlaceholderText(_translate("MainWindow", "Please Enter Member ID"))
        self.label_meber_name.setText(_translate("MainWindow", "Member name"))
        self.label_contact_info.setText(_translate("MainWindow", "Contact Info"))
        self.toolButton_issue.setText(_translate("MainWindow", "Issue Book"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Issue Book"))
        self.lineEdit_submission.setPlaceholderText(_translate("MainWindow", "Please Enter Book ID"))
        item = self.tableWidget_book_info.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Book ID"))
        item = self.tableWidget_book_info.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Member ID"))
        item = self.tableWidget_book_info.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Issue Time"))
        item = self.tableWidget_book_info.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Renew Count"))
        self.toolButton_renew.setText(_translate("MainWindow", "Renew Book"))
        self.toolButton_submit_book.setText(_translate("MainWindow", "Submit Book"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Renew/Submission Book"))
        self.toolButton_add_member.setText(_translate("MainWindow", "Add Member"))
        self.toolButton_add_book.setText(_translate("MainWindow", "Add Book"))
        self.toolButton_view_books.setText(_translate("MainWindow", "View Books"))
        self.toolButton_view_memers.setText(_translate("MainWindow", "View Members"))
